# config/packages/framework.yaml
framework:
    session:
        # enables the support of sessions in the app
        enabled: true
        # ID of the service used for session storage.
        # NULL means that Symfony uses PHP default session mechanism
        handler_id: null
        # ...
        # lifetime in seconds
        cookie_lifetime: 172800